# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  SUPABASE_PASS: ${{ secrets.SUPABASE_PASS }}
  SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
  PORT: ${{ secrets.PORT }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: npm ci
    - run: npm test
    - name: Deploy production to Netlify
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: movie-lib-aji.rivaldy.space
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password}}
        server-dir: /movie-lib-dir-aji/
        # NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        # NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        # NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
        # NETLIFY_DEPLOY_TO_PROD: true